#!/usr/bin/env python3
"""
post_review.py
Reads llm_result.json and posts a GitHub Pull Request Review with
a summary comment + per-line annotations via the GitHub REST API.
"""

import json
import os
import pathlib
import sys

import requests

# ── Configuration ─────────────────────────────────────────────────────────────
GH_TOKEN        = os.environ["GH_TOKEN"]
REPO            = os.environ["REPO"]
PR_NUMBER       = os.environ["PR_NUMBER"]
HEAD_SHA        = os.environ["HEAD_SHA"]
FAIL_SEVERITY   = os.environ.get("LLM_FAIL_SEVERITY", "major")

SEVERITY_ORDER = ["nit", "minor", "major", "critical"]
SEVERITY_EMOJI = {
    "critical": "🔴",
    "major":    "🟠",
    "minor":    "🟡",
    "nit":      "⚪",
}
LABEL_EMOJI = {
    "security":    "🔒",
    "sad-path":    "⚠️",
    "performance": "⚡",
    "consistency": "📐",
    "correctness": "🐛",
    "tests":       "🧪",
}

GH_API = "https://api.github.com"
HEADERS = {
    "Authorization":        f"Bearer {GH_TOKEN}",
    "Accept":               "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
}


def threshold_index() -> int:
    try:
        return SEVERITY_ORDER.index(FAIL_SEVERITY)
    except ValueError:
        return SEVERITY_ORDER.index("major")


def has_blocking_issues(comments: list) -> bool:
    idx = threshold_index()
    return any(
        SEVERITY_ORDER.index(c.get("severity", "nit")) >= idx
        for c in comments
    )


def format_labels(labels: list) -> str:
    if not labels:
        return ""
    parts = [f"{LABEL_EMOJI.get(lb, '•')} `{lb}`" for lb in labels]
    return "  " + "  ".join(parts)


def build_comment_body(c: dict) -> str:
    sev   = c.get("severity", "nit")
    emoji = SEVERITY_EMOJI.get(sev, "⚫")
    title = c.get("title", "Issue")
    body  = c.get("body", "")
    label_str  = format_labels(c.get("labels", []))
    patch      = c.get("suggested_patch", "")
    tests      = c.get("tests_suggested", [])

    parts = [
        f"{emoji} **[{sev.upper()}] {title}**{label_str}\n",
        body,
    ]

    if patch:
        # Use GitHub's suggestion syntax when patch looks like a code snippet
        if patch.startswith("-") or patch.startswith("+"):
            parts.append(f"\n```suggestion\n{patch}\n```")
        else:
            parts.append(f"\n**Suggested fix:**\n```ruby\n{patch}\n```")

    if tests:
        parts.append("\n**Tests to add:**")
        for t in tests:
            parts.append(f"```ruby\n{t}\n```")

    return "\n".join(parts)


def build_summary(result: dict, blocking: bool) -> str:
    verdict    = result.get("verdict", "pass")
    summary    = result.get("summary", "")
    stats      = result.get("stats", {})
    confidence = int(result.get("confidence", 0) * 100)
    comments   = result.get("comments", [])

    icon = "✅" if verdict == "pass" else "❌"

    # Issue breakdown by severity
    breakdown = {}
    for c in comments:
        sev = c.get("severity", "nit")
        breakdown[sev] = breakdown.get(sev, 0) + 1

    breakdown_str = "  ".join(
        f"{SEVERITY_EMOJI.get(s, '•')} {breakdown[s]} {s}"
        for s in ["critical", "major", "minor", "nit"]
        if s in breakdown
    ) or "none"

    lines = [
        f"## {icon} LLM Code Review — {verdict.replace('_', ' ').title()}",
        "",
        f"> {summary}",
        "",
        f"| Files reviewed | Issues found | Confidence |",
        f"|----------------|--------------|------------|",
        f"| {stats.get('files_reviewed', 0)} | {stats.get('issues_found', 0)} | {confidence}% |",
        "",
        f"**By severity:** {breakdown_str}",
    ]

    if blocking:
        lines += [
            "",
            f"> ⛔ This PR has issues at or above the configured threshold "
            f"(`LLM_FAIL_SEVERITY={FAIL_SEVERITY}`). "
            f"Add the `override/llm` label to bypass.",
        ]
    else:
        lines += ["", "> ℹ️ No blocking issues found. Minor/nit comments are advisory."]

    lines += [
        "",
        "<details><summary>About this review</summary>",
        "",
        "This review was generated by an LLM. It focuses on logic correctness, "
        "sad-path handling, security, and performance — not style (handled by RuboCop). "
        "False positives are possible. Use the `skip-llm` label to skip future reviews "
        "on trivial PRs.",
        "</details>",
    ]

    return "\n".join(lines)


def get_pr_files_with_patch_lines() -> dict[str, set[int]]:
    """
    Fetch the list of files in this PR from GitHub and return a mapping of
    filepath -> set of line numbers that appear in the diff (RIGHT side).
    Used to validate that our annotation lines are actually in the diff.
    """
    url = f"{GH_API}/repos/{REPO}/pulls/{PR_NUMBER}/files"
    resp = requests.get(url, headers=HEADERS, params={"per_page": 100})
    resp.raise_for_status()

    valid_lines: dict[str, set[int]] = {}
    for file_info in resp.json():
        path  = file_info.get("filename", "")
        patch = file_info.get("patch", "")
        if not patch:
            continue
        lines = set()
        current_new_line = 0
        for pline in patch.splitlines():
            if pline.startswith("@@"):
                import re
                m = re.search(r'\+(\d+)', pline)
                if m:
                    current_new_line = int(m.group(1)) - 1
            elif pline.startswith("-"):
                pass  # deleted lines don't have a new-side line number
            else:
                current_new_line += 1
                lines.add(current_new_line)
        valid_lines[path] = lines

    return valid_lines


def post_review(summary_body: str, line_comments: list, event: str):
    url  = f"{GH_API}/repos/{REPO}/pulls/{PR_NUMBER}/reviews"
    data = {
        "commit_id": HEAD_SHA,
        "body":      summary_body,
        "event":     event,
        "comments":  line_comments,
    }
    resp = requests.post(url, headers=HEADERS, json=data)
    if not resp.ok:
        print(f"  GitHub API error {resp.status_code}: {resp.text[:500]}")
        resp.raise_for_status()
    return resp.json()


# ── Main ──────────────────────────────────────────────────────────────────────
def main():
    result_path = pathlib.Path("llm_result.json")
    if not result_path.exists():
        sys.exit("llm_result.json not found. Run call_llm.py first.")

    result   = json.loads(result_path.read_text())
    comments = result.get("comments", [])
    blocking = has_blocking_issues(comments)

    # Fetch which lines are valid for annotation
    try:
        valid_lines = get_pr_files_with_patch_lines()
    except Exception as e:
        print(f"  Warning: could not fetch PR file list for line validation: {e}")
        valid_lines = {}

    # Build per-line review comments (only for lines present in the diff)
    line_comments = []
    file_level_comments = []

    for c in comments:
        file  = c.get("file")
        line  = c.get("line")
        body  = build_comment_body(c)

        if file and line:
            # Validate line is in the diff
            if file in valid_lines and line in valid_lines[file]:
                line_comments.append({
                    "path": file,
                    "line": line,
                    "side": "RIGHT",
                    "body": body,
                })
            else:
                # Demote to file-level if line not in diff
                file_level_comments.append({
                    "path": file,
                    "body": f"_(line {line} not in diff — shown as file comment)_\n\n{body}",
                    "subject_type": "file",
                })
        elif file:
            file_level_comments.append({
                "path": file,
                "body": body,
                "subject_type": "file",
            })

    all_comments = line_comments + file_level_comments
    summary_body = build_summary(result, blocking)
    event        = "REQUEST_CHANGES" if blocking else "COMMENT"

    print(f"  Posting review: event={event}  |  "
          f"line_comments={len(line_comments)}  |  "
          f"file_comments={len(file_level_comments)}")

    review = post_review(summary_body, all_comments, event)
    print(f"  Review posted successfully: id={review.get('id')}  "
          f"url={review.get('html_url', '')}")


if __name__ == "__main__":
    main()
