module Dradis::Plugins::Echo
  class Message < ApplicationRecord
    enum :role, %i[user assistant]
    enum :status, %i[complete streaming failed], default: :complete

    store :metadata, coder: JSON

    # -- Relationships --------------------------------------------------------
    belongs_to :parent, class_name: 'Dradis::Plugins::Echo::Message', optional: true
    belongs_to :session
    belongs_to :user, optional: true

    # -- Callbacks ------------------------------------------------------------
    # User messages are authored in full, so they're never mid-stream.
    before_validation :complete_user_messages

    after_create_commit :broadcast_created

    # -- Validations ----------------------------------------------------------
    validates :content, presence: true, if: :complete?
    # Assistant messages are generated by the agent, never a user.
    validates :user_id, absence: true, if: :assistant?

    # -- Instance Methods -----------------------------------------------------

    private

    def broadcast_created
      broadcast_append_to(
        [session, :messages],
        target: 'echo-messages',
        partial: 'dradis/plugins/echo/projects/sessions/messages/message',
        locals: { message: self }
      )
      # Retire the first-paint "thinking" sentinel now that a real message has
      # landed, so the two are never shown together. A no-op when it's absent
      # (every follow-up message), and terminal-state-safe: an explicit remove
      # (vs a CSS :has() rule) can't let the sentinel reappear once the real
      # bubble stops streaming (streaming -> complete/failed) — SEC-508.
      broadcast_remove_to(
        [session, :messages],
        target: ActionView::RecordIdentifier.dom_id(session, :pending_reply)
      )
    end

    def complete_user_messages
      self.status = :complete if user?
    end
  end
end
