module Dradis::Plugins::Echo
  class Message < ApplicationRecord
    enum :role, %i[user assistant]
    enum :status, %i[complete streaming failed], default: :complete

    store :metadata, coder: JSON

    # -- Relationships --------------------------------------------------------
    belongs_to :parent, class_name: 'Dradis::Plugins::Echo::Message', optional: true
    belongs_to :session
    belongs_to :user, optional: true

    # -- Callbacks ------------------------------------------------------------
    # User messages are authored in full, so they're never mid-stream.
    before_validation :complete_user_messages, if: :user?

    after_create_commit :broadcast_created

    # -- Validations ----------------------------------------------------------
    validates :content, presence: true, if: :complete?
    # Assistant messages are generated by the agent, never a user.
    validates :user_id, absence: true, if: :assistant?

    # -- Instance Methods -----------------------------------------------------

    private

    def broadcast_created
      broadcast_append_to(
        [session, :messages],
        target: 'echo-messages',
        partial: 'dradis/plugins/echo/projects/sessions/messages/message',
        locals: { message: self }
      )
    end

    def complete_user_messages
      self.status = :complete
    end
  end
end
