name: "dradis-ce-dev"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      platforms:
        - linux/amd64
    command: sleep infinity
    ports:
      - "3000:3000"
    environment:
      - SELENIUM_HOST=selenium
    volumes:
      - ..:/workspace
  selenium:
    image: selenium/standalone-firefox
    restart: unless-stopped
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"
