name: "dradis-ce-dev"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      platforms:
        - linux/amd64
    command: sleep infinity
    ports:
      - "3000:3000"
    volumes:
      - ..:/workspace
