development:
  adapter: <%= defined?(Dradis::Pro) ? 'redis' : 'async' %>
  url: <%= ENV.fetch('REDIS_URL') { 'redis://localhost:6379/1' } %>

test:
  adapter: test

production:
  adapter: <%= defined?(Dradis::Pro) ? 'redis' : 'async' %>
  url: <%= ENV.fetch('REDIS_URL') { 'redis://localhost:6379/1' } %>
  channel_prefix: dradispro_production
